# Generated by Django 2.2.3 on 2020-11-27 06:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_block',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Date_of_birth', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Location', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('Phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
