# Generated by Django 2.2.3 on 2020-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(default='', max_length=50)),
                ('Location', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=50)),
                ('stipend', models.IntegerField(default=0)),
                ('city', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
