# Generated by Django 2.2.3 on 2020-11-29 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0002_customer_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('adhaar_card', models.CharField(default='', max_length=50)),
                ('pan_card', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('Date_of_birth', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Date_of_apply', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('Approve', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
