# Generated by Django 2.2.3 on 2020-11-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0004_loan_data_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_data',
            name='Date_of_apply',
        ),
        migrations.RemoveField(
            model_name='loan_data',
            name='Date_of_birth',
        ),
    ]
