# Generated by Django 2.2.3 on 2020-12-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0005_auto_20201130_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='Date_of_apply',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
