# Generated by Django 2.2.3 on 2020-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0007_auto_20201203_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='total_interest',
            field=models.CharField(default='', max_length=50),
        ),
    ]
