# Generated by Django 2.2.3 on 2020-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RC_loan', '0008_loan_data_total_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
